# Generated by Django 4.0.4 on 2022-05-31 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('inputtype', models.CharField(choices=[('textbox', 'TextBox'), ('textarea', 'TextArea'), ('boolean', 'Boolean'), ('radiobutton', 'RadioButton'), ('checkbox', 'CheckBox'), ('select', 'Select'), ('multiselect', 'MultiSelect')], max_length=100, verbose_name='Input Type')),
                ('required', models.BooleanField()),
            ],
        ),
    ]
