# Generated by Django 4.0.4 on 2022-06-02 09:25

import attribute.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('language', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('inputtype', models.CharField(choices=[('textbox', 'TextBox'), ('textarea', 'TextArea'), ('boolean', 'Boolean'), ('radiobutton', 'RadioButton'), ('checkbox', 'CheckBox'), ('select', 'Select'), ('multiselect', 'MultiSelect')], max_length=100, verbose_name='Input Type')),
                ('required', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customOption', models.CharField(max_length=100, unique=True, verbose_name='Custom Option')),
                ('sortOrder', models.IntegerField(default=0, verbose_name='Sort Order')),
                ('default', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=100)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attribute.attribute')),
            ],
        ),
        migrations.CreateModel(
            name='OptionTranslation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Option Name')),
                ('language', models.ForeignKey(default=attribute.models.get_lang, on_delete=django.db.models.deletion.CASCADE, to='language.language')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attribute.option')),
            ],
            options={
                'verbose_name': 'Option Translation',
                'unique_together': {('language', 'option')},
            },
        ),
        migrations.CreateModel(
            name='AttributeTranslation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Attribute Name')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attribute.attribute')),
                ('language', models.ForeignKey(default=attribute.models.get_lang, on_delete=django.db.models.deletion.CASCADE, to='language.language')),
            ],
            options={
                'verbose_name': 'Attribute Translation',
                'unique_together': {('language', 'attribute')},
            },
        ),
    ]
