# Generated by Django 4.0.4 on 2022-06-02 09:21

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('language', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', max_length=10)),
                ('sortOrder', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PageTranslation',
            fields=[
                ('ptId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', tinymce.models.HTMLField()),
                ('languageCode', models.ForeignKey(limit_choices_to={'active': 'yes'}, on_delete=django.db.models.deletion.CASCADE, to='language.language')),
                ('page', models.ForeignKey(limit_choices_to={'status': 'enabled'}, on_delete=django.db.models.deletion.CASCADE, to='page.page')),
            ],
            options={
                'unique_together': {('languageCode', 'page')},
            },
        ),
    ]
