# Generated by Django 4.0.4 on 2022-05-31 04:51

from django.db import migrations, models
import django.db.models.deletion
import optionTranslation.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('language', '0001_initial'),
        ('attribute', '0001_initial'),
        ('option', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionTranslation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Option Name')),
                ('attribute', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='attribute.attribute')),
                ('language', models.ForeignKey(default=optionTranslation.models.get_lang, on_delete=django.db.models.deletion.CASCADE, to='language.language')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='option.option')),
            ],
            options={
                'verbose_name': 'Option Translation',
                'unique_together': {('language', 'option')},
            },
        ),
    ]
