# Generated by Django 4.0.4 on 2022-05-31 04:48

import attributeTranslation.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attribute', '0001_initial'),
        ('language', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeTranslation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Attribute Name')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attribute.attribute')),
                ('language', models.ForeignKey(default=attributeTranslation.models.get_lang, on_delete=django.db.models.deletion.CASCADE, to='language.language')),
            ],
            options={
                'verbose_name': 'Attribute Translation',
                'unique_together': {('language', 'attribute')},
            },
        ),
    ]
